FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY client/package.json client/package.json
COPY server/package.json server/package.json
COPY engine/package.json engine/package.json
COPY shared/package.json shared/package.json

RUN npm install

COPY . .

EXPOSE 3001

CMD ["npm", "--workspace", "server", "run", "dev"]

